### ISSUE TITLE
Crash on loading minecraft 1.11

### ISSUE THREAD

**Issue by Wizardon777** [meza/achievementbooks#10]
client crashes on loading whilst using a book containig those lines:

```
{
    "itemName": "sky_arsenal_book",
    "bookName": "Sky arsenal Achievements",
	"color": "deepblue",
	"craftingMaterial": "minecraft:cobblestone",
    "pages": [
		[
			{
				"id": 1,
				"header": "Welcome to Sky Arsenal",
				"description": "With this book you'll get to check off your achievements and show your progress to the world!"
			},
			{
				"id": 2,
				"description": "Make your way through the game while keeping note on what you're doing"
			}
		],
        [
			{
				"id": 3,
				"header": "Starting up",
			},
			{
				"id": 4,
				"achievement": "Twerk near a sapling, Make it grow!",
				"mod": "vanilla"
			}
		],
        []
    ]
}

```

Crash Report:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  GudLib (gud_lib-1.2.0.0.jar)
  ForgelinPlugin (Forgelin-1.4.0.jar)
  RebornCoreASM (RebornCore-1.11.2-2.13.5.42-universal.jar)
  LoadingPlugin (Quark-r1.2-87.jar)
  LoadingPlugin (RandomThings-MC1.11.2-3.8.1.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  CorePlugin (FluxedRedstone-2.6.0.54.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.3.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-78.jar)
  MDECore-Core (mdecore-1.11-1.0.jar)
  RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  SFRCore (SolarFluxReborn_1.11.2-2.15r.jar)
  LoadingPlugin (ResourceLoader-MC1.11-1.5.1.jar)
  LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.11.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 3/25/17 1:27 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Achievement Books (achievementbooks)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 22 column 5
	at com.google.gson.internal.Streams.parse(Streams.java:56)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:54)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:741)
	at com.stateshifterlabs.achievementbooks.data.Loader.init(Loader.java:101)
	at com.stateshifterlabs.achievementbooks.data.Loader.init(Loader.java:43)
	at com.stateshifterlabs.achievementbooks.AchievementBooksMod.init(AchievementBooksMod.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:828)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 22 column 5
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:494)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:659)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:659)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:667)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642)
	at com.google.gson.internal.Streams.parse(Streams.java:44)
	... 42 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2715913000 bytes (2590 MB) / 3649044480 bytes (3480 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2260 130 mods loaded, 129 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2260.jar) 
	UCHI	forge{13.20.0.2260} [Minecraft Forge] (forge-1.11.2-13.20.0.2260.jar) 
	UCHI	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHI	gud_lib{1.2.0.0} [GudLib] (gud_lib-1.2.0.0.jar) 
	UCHE	achievementbooks{1.0b82-MC1.11.2} [Achievement Books] (achievementbooks-1.0b82-MC1.11.2.jar) 
	UCHI	achunkloader{1.11-1.2.0} [A Chunk Loader] (achunkloader-1.11.2-1.2.0.jar) 
	UCHI	actuallyadditions{1.11.2-r106} [Actually Additions] (ActuallyAdditions-1.11.2-r106.jar) 
	UCHI	alltheblocks{1.11.2-1.1.0} [All the Blocks] (alltheblocks-1.11.2-1.1.0.jar) 
	UCHI	jei{4.2.10.248} [Just Enough Items] (jei_1.11.2-4.2.10.248.jar) 
	UCHI	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCHI	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UCHI	forgelin{1.4.0} [Forgelin] (Forgelin-1.4.0.jar) 
	UCHI	thedragonlib{1.11.2-3.1.1} [TheDragonLib] (thedragonlib-1.11.2-3.1.1.jar) 
	UCHI	armorplus{1.11.2-10.1.2.3} [ArmorPlus] (armorplus-1.11.2-10.1.2.3.jar) 
	UCHI	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHI	aroma1997sdimension{1.0} [Aroma1997sDimension] (Aroma1997s-Dimensional-World-1.11.2-1.3.0.0.b31.jar) 
	UCHI	mdecore{1.11-1.0} [MattDahEpic Core] (mdecore-1.11-1.0.jar) 
	UCHI	autooredictconv{1.11-1.0.2} [Auto Ore Dictionary Converter] (autooredictconv-1.11-1.0.2.jar) 
	UCHI	quark{r1.2-87} [Quark] (Quark-r1.2-87.jar) 
	UCHI	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHI	betterachievements{0.4.3.12} [Better Achievements] (BetterAchievements-1.11.2-0.4.3.12.jar) 
	UCHI	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.11-0.11.1.239+9162f74.jar) 
	UCHI	birdsnests{1.5.1} [Bird's Nests] (BirdsNests1.11.2-1.5.1.jar) 
	UCHI	guideapi{1.11-2.1.0-51} [Guide-API] (Guide-API-1.11-2.1.0-51.jar) 
	UCHI	bloodmagic{1.11-2.1.7-76} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.7-76.jar) 
	UCHI	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.11-1.5.1.jar) 
	UCHI	botania{r1.9-342} [Botania] (Botania r1.9-342.jar) 
	UCHI	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCHI	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHI	chancecubes{1.11-2.3.3.136} [Chance Cubes] (ChanceCubes-1.11-2.3.3.136.jar) 
	UCHI	chesttransporter{2.7.1} [Chest Transporter] (ChestTransporter-1.11.2-2.7.1.jar) 
	UCHI	chisel{MC1.11.2-0.0.9.11} [Chisel] (Chisel-MC1.11.2-0.0.9.11.jar) 
	UCHI	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	UCHI	claybucket{1.1} [Clay Bucket] (ClayBucket-1.11-1.0.jar) 
	UCHI	cyclopscore{0.10.0} [Cyclops Core] (CyclopsCore-1.11.2-0.10.0.jar) 
	UCHI	colossalchests{1.5.0} [Colossal Chests] (ColossalChests-1.11.2-1.5.0.jar) 
	UCHI	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.11.2-3.0.24.jar) 
	UCHI	crafttweaker{3.0.24} [Crafttweaker] (CraftTweaker-1.11.2-3.0.24.jar) 
	UCHI	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.11.2-3.0.24.jar) 
	UCHI	custommainmenu{2.0.3} [Custom Main Menu] (CustomMainMenu-MC1.11-2.0.3.jar) 
	UCHI	cyclicmagic{1.2.3} [Cyclic] (Cyclic-1.11.2-1.2.3.jar) 
	UCHI	forestry{5.3.2.60} [Forestry] (forestry_1.11.2-5.3.2.60.jar) 
	UCHI	eleccore{1.7.409} [ElecCore] (ElecCore-1.11-1.7.409.jar) 
	UCHI	deepresonance{1.4.6} [DeepResonance] (deepresonance-1.1x-1.4.6.jar) 
	UCHI	durabilityshow{4.1.0} [Durability Show] (Durability Show-1.11.2-4.1.0.jar) 
	UCHI	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod-1.11.2-1.3.0.jar) 
	UCHI	fecm{1.0.0} [Elytra Crafting Recipe Mod] (Elytra Crafting Mod-1.0.0.jar) 
	UCHI	valkyrielib{1.11.2-0.11.0b} [Valkyrie Lib] (valkyrielib-1.11.2-0.11.0c.jar) 
	UCHI	environmentaltech{1.11.2-0.11.0d} [Environmental Tech] (environmentaltech-1.11.2-0.11.0d.jar) 
	UCHI	etlunar{1.11.2-0.11.0c} [ET Lunar] (etlunar-1.11.2-0.11.0c.jar) 
	UCHI	exparvis{0.3.0} [Ex Parvis] (exparvis-1.11-0.3.0.jar) 
	UCHI	extrabitmanipulation{1.11.2-3.0.5} [Extra Bit Manipulation] (ExtraBitManipulation-1.11.2-3.0.5.jar) 
	UCHI	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.3.3.jar) 
	UCHI	zerocore{1.11.2-0.1.0.4} [Zero CORE] (zerocore-1.11.2-0.1.0.4.jar) 
	UCHI	bigreactors{1.11.2-0.4.5.27} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.27.jar) 
	UCHI	fl{1.0.1} [FL] (fl-1.0.1.jar) 
	UCHI	flourpower{1.11-0.0.3-2} [Flour Power] (FlourPower-1.11-0.0.3-2.jar) 
	UCHI	reborncore{2.13.5.42} [RebornCore] (RebornCore-1.11.2-2.13.5.42-universal.jar) 
	UCHI	reborncore-mcmultipart{2.13.5.42} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.13.5.42-universal.jar) 
	UCHI	fluxedredstone{@MODVERSION@} [FluxedRedstone] (FluxedRedstone-2.6.0.54.jar) 
	UCHI	gardenofglass{sqrt(-1)} [Garden of Glass] (GardenOfGlass.jar) 
	UCHI	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCHI	grue{1.3.4} [Grue] (Grue-1.11.2-1.3.4.jar) 
	UCHI	gud_coolers{2.0.0.4} [Coolers] (gud_coolers-2.0.0.4.jar) 
	UCHI	hammercore{1.4.3} [Hammer Core] (HammerCore_1.11.2-1.4.3.jar) 
	UCHI	hcmw{1.0} [Homecraft Mineware] (hcmw-1.11.2-0.2.9-universal.jar) 
	UCHI	waila{1.8.10} [Waila] (Hwyla-1.8.10-B23_1.11.jar) 
	UCHI	inventorytweaks{1.62-dev-78-e073cca} [Inventory Tweaks] (InventoryTweaks-1.62-dev-78.jar) 
	UCHI	ironchest{1.11.2-7.0.18.800} [Iron Chest] (ironchest-1.11.2-7.0.18.800.jar) 
	UCHI	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.11.2.jar) 
	UCHI	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHI	loottweaker{0.0.5} [LootTweaker] (LootTweaker-1.11.2-0.0.5.jar) 
	UCHI	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	UCHI	kleeslabs{4.3.5} [KleeSlabs] (KleeSlabs_1.11.2-4.3.5.jar) 
	UCHI	levels{r1.2.8} [Levels] (Levels 2-1.11.2-r1.2.8.jar) 
	UCHI	levelup{${version}} [Level Up!] (LevelUp!-0.14.3-1.11.2.jar) 
	UCHI	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
	UCHI	mcflux{2.6.0} [Minecraft-Flux] (mcflux-2.6.0.jar) 
	UCHI	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.11.2.jar) 
	UCHI	mtlib{@VERSION@} [MTLib] (MTLib-2.0.1.jar) 
	UCHI	shetiphiancore{3.4.3} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.3.jar) 
	UCHI	terraqueous{1.3.8} [Terraqueous] (terraqueous-1.11.0-1.3.8.jar) 
	UCHI	multistorage{1.3.5} [Multi-Storage] (multistorage-1.11.0-1.3.5.jar) 
	UCHI	mysticalagriculture{1.4.5} [Mystical Agriculture] (mysticalagriculture[1.11.2]-1.4.5.jar) 
	UCHI	nmsot{1.2.0-mc1.11.2} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.0-mc1.11.2.jar) 
	UCHI	notenoughwands{1.5.4} [Not Enough Wands] (notenoughwands-1.1x-1.5.4.jar) 
	UCHI	orecore{0.5.0} [§6Ore Core] (Ore Core 1.11.2 (v.0.5.0).jar) 
	UCHI	oreexcavation{1.3.85} [OreExcavation] (OreExcavation-1.3.85.jar) 
	UCHI	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2g.jar) 
	UCHI	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.11.2-1.2.3.jar) 
	UCHI	randomthings{3.8.1} [Random Things] (RandomThings-MC1.11.2-3.8.1.jar) 
	UCHI	rarmor{1.11.2-r4.3} [Rarmor] (Rarmor-1.11.2-r4.3.jar) 
	UCHI	refinedstorage{1.4.1} [Refined Storage] (refinedstorage-1.4.1.jar) 
	UCHI	xreliquary{1.11.2-1.3.3.635} [Reliquary] (Reliquary-1.11.2-1.3.3.635.jar) 
	UCHI	resourceloader{1.5.1} [Resource Loader] (ResourceLoader-MC1.11-1.5.1.jar) 
	UCHI	rftools{5.90} [RFTools] (rftools-1.1x-5.90.jar) 
	UCHI	rftoolscontrol{1.6.6} [RFTools Control] (rftoolsctrl-1.1x-1.6.6.jar) 
	UCHI	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55.jar) 
	UCHI	riteclicker{1.11.2_1} [Rite Clicker] (RiteClicker-1.11.2_1.jar) 
	UCHI	roots{0.014} [Roots 2] (roots-2-0.014.jar) 
	UCHI	seeddrop{1.1.0-1.10} [SeedDrop] (SeedDrop-1.1.0-1.11.jar) 
	UCHI	simplegenerators{1.11.2-0.11.0a} [Simple Generators] (simplegenerators-1.11.2-0.11.0a.jar) 
	UCHI	simpleleather{1.11.2-1.0} [Simple Leather] (simpleleather-1.11.2-1.0.jar) 
	UCHI	simplyconveyors{2.1.0} [Simply Conveyors] (SimplyConveyors-2.1.2.jar) 
	UCHI	skyresources{1.6.0} [Sky Resources] (skyresources-1.6.0.jar) 
	UCHI	solarfluxreborn{2.15r} [Solar Flux Reborn] (SolarFluxReborn_1.11.2-2.15r.jar) 
	UCHI	stellarapi{0.6.4.1.3} [Stellar API] (Stellar API-0.6.4.1.3.jar) 
	UCHI	stellarsky{0.6.5.1.4} [Stellar Sky] (Stellar Sky-0.6.5.1.4.jar) 
	UCHI	storagedrawers{1.11.2-4.2.0} [Storage Drawers] (StorageDrawers-1.11.2-4.2.0.jar) 
	UCHI	substratum{1.9.2.0} [Substratum] (Substratum-1.11.2-1.9.2.0.jar) 
	UCHI	supplydrop{1.0.1} [Supply Drop] (Supply Drop-1.11.2-1.0.1.jar) 
	UCHI	techexpansion{1.5} [Tech Expansion] (techexpansion-1.5.jar) 
	UCHI	techreborn{2.1.10.88} [TechReborn] (TechReborn-1.11.2-2.1.10.88-universal.jar) 
	UCHI	beneath{1.2.0} [The Beneath] (The Beneath-1.11.2-1.2.0.jar) 
	UCHI	theoneprobe{1.4.5} [The One Probe] (theoneprobe-1.1x-1.4.5.jar) 
	UCHI	timehud{7.2.1} [Time HUD] (TimeHUD-Forge-1.11.2-7.2.1.jar) 
	UCHI	tp{2.0.2} [Tiny Progressions] (tinyprogressions-1.11.2-2.0.2.jar) 
	UCHI	muchmorechickens{1.4} [muchmorechickens] (TMC-1.11.2-1.4.jar) 
	UCHI	toolupgrades{1.2.1} [§9Tool-Upgrades Mod] (Tool Upgrades 1.11.2 (v.1.2.1).jar) 
	UCHI	torchmaster{1.0} [TorchMaster] (torchmaster_1.11.2-1.2.0.19.jar) 
	UCHI	transporter{1.0.0} [Transporter] (transporter-1.11.2-1.0.0.1.jar) 
	UCHI	ts2k16{1.1.4} [Twerk-Sim 2K16] (TS2K16-1.1.4.jar) 
	UCHI	uncrafted{2.1.9} [Uncrafted Mod] (Uncrafted 1.11.2 (v.2.1.9).jar) 
	UCHI	voidislandcontrol{1.1.3} [Void Island Control] (voidislandcontrol-1.1.3.jar) 
	UCHI	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	UCHI	weaponcaseloot{5.0.3-beta} [WeaponCaseLoot] (weaponcaseloot-1.11.2-5.0.3-beta.jar) 
	UCHI	xnet{1.1.2} [XNet] (xnet-1.1.2.jar) 
	UD	mdecore-core{1.0} [MDE Core - ASM Tweaks] (minecraft.jar) 
	Loaded coremods (and transformers): 
GudLib (gud_lib-1.2.0.0.jar)
  net.gudenau.lib.core.ClientTransformer
ForgelinPlugin (Forgelin-1.4.0.jar)
  
RebornCoreASM (RebornCore-1.11.2-2.13.5.42-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
LoadingPlugin (Quark-r1.2-87.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.11.2-3.8.1.jar)
  lumien.randomthings.asm.ClassTransformer
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  
CorePlugin (FluxedRedstone-2.6.0.54.jar)
  
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.3.jar)
  shetiphian.core.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.62-dev-78.jar)
  invtweaks.forge.asm.ContainerTransformer
MDECore-Core (mdecore-1.11-1.0.jar)
  com.mattdahepic.mdecore.asm.TickrateTransformer
RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  pw.prok.realbench.asm.RBTransformer
SFRCore (SolarFluxReborn_1.11.2-2.15r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
LoadingPlugin (ResourceLoader-MC1.11-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.11.jar)
  team.chisel.common.asm.ChiselTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.92' Renderer: 'GeForce GTX 780 Ti/PCIe/SSE2'
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.13.5.42
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 0
```

**Comment by meza** [comment]
Hello.

If you look at the Crash Report, the **Caused by** tells you there's a JsonSyntaxError.

You can go to http://jsonlint.com/ and validate your config there to see where the error is

**Comment by Wizardon777** [comment]
ty!
there was a "," where there should no have been!
